stages:
     - build
     - test

build-job :
     stage: build
     tags:
         - grad
     script:
         - cd Group20
         - mvn clean package -DskipTests

test-job:
    stage: test
    tags:
         - grad
    script:
        - cd Group20
        - mvn clean verify      

