stages:
     - build
     - test

build-job :
     stage: build
     tags:
         - ugrad
     script:
         -cd Group20
         -mvn clean package -DskipTests

test-job:
    stage: test
    tags:
         - ugrad
    script:
        -cd Group20
        -mvn clean verify      

